import type { DemoFloorPost } from "./types";

/** Static marketing examples — never fetched from Supabase. */
export const DEMO_FLOOR_POSTS: DemoFloorPost[] = [
  {
    id: "demo-nvda-split",
    isDemo: true,
    author: { id: "demo-1", displayName: "Night shift desk" },
    shiftId: null,
    runId: null,
    watchlistId: null,
    postKind: "shift" as const,
    caption: "Committee fractured on NVDA — weather held until debate broke the tie.",
    tickers: ["NVDA"],
    model: "anthropic/claude-sonnet-4",
    analystCount: 12,
    tsMs: Date.UTC(2026, 5, 8, 2, 30),
    heroArtifactUrl: null,
    likeCount: 0,
    commentCount: 0,
    publishedAt: "2026-06-08T02:30:00.000Z",
    snapshot: {
      ephemeralArtifactWarnings: [],
      artifacts: [
        {
          id: "committee_dispersion",
          title: "NVDA committee dispersion",
          caption: "Bull/bear/neutral split across 10 desks; confidence spread 38 pts.",
          kind: "committee_dispersion",
          data: {
            ticker: "NVDA",
            bullish: 4,
            bearish: 3,
            neutral: 3,
            confidence_spread: 38,
            confidence_avg: 71,
            opinions: [
              { agent: "Warren Buffett", signal: "bearish", confidence: 82 },
              { agent: "Cathie Wood", signal: "bullish", confidence: 88 },
              { agent: "Michael Burry", signal: "bearish", confidence: 79 },
              { agent: "Peter Lynch", signal: "bullish", confidence: 74 },
            ],
          },
        },
      ],
      tickers: [
        {
          ticker: "NVDA",
          bossDecision: {
            action: "hold",
            confidence: 62,
            reasoning:
              "Desk conviction insufficient after debate — maintain watch position until hyperscaler capex cycle clarifies.",
            quantity: 0,
          },
          price: 118.42,
          summaryLine: { ticker: "NVDA", action: "hold", confidence: 62 },
          opinions: [
            {
              agentKey: "cathie_wood",
              agentName: "Cathie Wood",
              signal: "bullish",
              confidence: 88,
              summary: "AI infra spend still accelerating; CUDA moat intact through 2027.",
            },
            {
              agentKey: "michael_burry",
              agentName: "Michael Burry",
              signal: "bearish",
              confidence: 79,
              summary: "Circular financing risk in hyperscaler GPU leases understates downside.",
            },
            {
              agentKey: "warren_buffett",
              agentName: "Warren Buffett",
              signal: "bearish",
              confidence: 82,
              summary: "Price embeds perfection; would need a clear margin-of-safety gap.",
            },
          ],
          tally: { bullish: 4, bearish: 3, neutral: 3 },
          weather: {
            ticker: "NVDA",
            condition: "variable",
            headline: "Variable winds — debate shifted conviction",
            fragility: 0.58,
            fragility_label: "Contested",
            tally: { bullish: 4, bearish: 3, neutral: 3 },
            carried_by: [
              { name: "Cathie Wood", signal: "bullish", confidence: 88 },
              { name: "Michael Burry", signal: "bearish", confidence: 79 },
            ],
            top_disputes: [
              { summary: "Capex durability vs circular lease financing" },
            ],
            dominant_claim: "AI infra spend trajectory",
            boss_action: "hold",
            boss_confidence: 62,
            voice_count: 10,
          },
          disputes: [{ summary: "Capex durability vs circular lease financing" }],
          debateRounds: [
            {
              ticker: "NVDA",
              left: {
                agent_id: "cathie_wood",
                name: "Cathie Wood",
                specialty: "growth",
                signal: "bullish",
                confidence_before: 88,
                confidence_after: 88,
              },
              right: {
                agent_id: "michael_burry",
                name: "Michael Burry",
                specialty: "contrarian",
                signal: "bearish",
                confidence_before: 79,
                confidence_after: 79,
              },
              lines: [],
              winner: "draw",
              winner_name: "Draw",
              summary: "Neither side conceded on capex financing risk.",
            },
          ],
        },
      ],
    },
  },
  {
    id: "demo-celh-bull",
    isDemo: true,
    author: { id: "demo-2", displayName: "Desk analyst" },
    shiftId: null,
    runId: null,
    watchlistId: null,
    postKind: "shift" as const,
    caption: "CELH cleared the committee — Lynch and Wood aligned on distribution inflection.",
    tickers: ["CELH"],
    model: "openai/gpt-4o",
    analystCount: 10,
    tsMs: Date.UTC(2026, 5, 5, 3, 15),
    heroArtifactUrl: null,
    likeCount: 0,
    commentCount: 0,
    publishedAt: "2026-06-05T03:15:00.000Z",
    snapshot: {
      ephemeralArtifactWarnings: [],
      artifacts: [
        {
          id: "price_target_fan",
          title: "CELH price target fan",
          caption: "Desk price targets vs spot — bullish cluster above $48.",
          kind: "price_target_fan",
          data: {
            ticker: "CELH",
            spot: 42.15,
            targets: [
              { agent: "Peter Lynch", target: 52, signal: "bullish" },
              { agent: "Cathie Wood", target: 49, signal: "bullish" },
              { agent: "Warren Buffett", target: 38, signal: "neutral" },
            ],
          },
        },
      ],
      tickers: [
        {
          ticker: "CELH",
          bossDecision: {
            action: "buy",
            confidence: 78,
            reasoning:
              "Distribution reset complete; same-store reacceleration with margin recovery supports a starter position.",
            quantity: 1200,
          },
          price: 42.15,
          summaryLine: { ticker: "CELH", action: "buy", confidence: 78 },
          opinions: [
            {
              agentKey: "peter_lynch",
              agentName: "Peter Lynch",
              signal: "bullish",
              confidence: 85,
              summary: "Shelf velocity improving; consumers trading down to functional energy.",
            },
            {
              agentKey: "cathie_wood",
              agentName: "Cathie Wood",
              signal: "bullish",
              confidence: 80,
              summary: "Brand heat on social still compounding; international whitespace.",
            },
          ],
          tally: { bullish: 7, bearish: 1, neutral: 2 },
          weather: {
            ticker: "CELH",
            condition: "clearing",
            headline: "Bull clearing — committee aligned",
            fragility: 0.22,
            fragility_label: "Stable consensus",
            tally: { bullish: 7, bearish: 1, neutral: 2 },
            carried_by: [{ name: "Peter Lynch", signal: "bullish", confidence: 85 }],
            top_disputes: [],
            dominant_claim: "Distribution inflection underway",
            boss_action: "buy",
            boss_confidence: 78,
            voice_count: 10,
          },
          disputes: [],
          debateRounds: [],
        },
      ],
    },
  },
  {
    id: "demo-meta-bear",
    isDemo: true,
    author: { id: "demo-3", displayName: "Risk desk" },
    shiftId: null,
    runId: null,
    watchlistId: null,
    postKind: "shift" as const,
    caption: "META short thesis — Taleb and Burry carried the bear cohort through scenarios.",
    tickers: ["META"],
    model: "google/gemini-2.5-pro",
    analystCount: 11,
    tsMs: Date.UTC(2026, 5, 2, 1, 45),
    heroArtifactUrl: null,
    likeCount: 0,
    commentCount: 0,
    publishedAt: "2026-06-02T01:45:00.000Z",
    snapshot: {
      ephemeralArtifactWarnings: [],
      artifacts: [
        {
          id: "scenario_tornado",
          title: "META scenario tornado",
          caption: "Regulatory fine and ad CPM shock dominate downside.",
          kind: "scenario_tornado",
          data: {
            ticker: "META",
            scenarios: [
              { label: "EU fine", impact_pct: -18 },
              { label: "CPM -12%", impact_pct: -14 },
              { label: "Reels monetization miss", impact_pct: -9 },
            ],
          },
        },
      ],
      tickers: [
        {
          ticker: "META",
          bossDecision: {
            action: "short",
            confidence: 71,
            reasoning:
              "Tail risks underpriced; regulatory and ad-cycle convexity favors a tactical short.",
            quantity: 400,
          },
          price: 512.3,
          summaryLine: { ticker: "META", action: "short", confidence: 71 },
          opinions: [
            {
              agentKey: "nassim_taleb",
              agentName: "Nassim Taleb",
              signal: "bearish",
              confidence: 84,
              summary: "Hidden convexity in regulatory tail; market prices mean reversion not blow-ups.",
            },
            {
              agentKey: "michael_burry",
              agentName: "Michael Burry",
              signal: "bearish",
              confidence: 76,
              summary: "Reality Labs burn unsustainable at current ad growth deceleration.",
            },
          ],
          tally: { bullish: 2, bearish: 6, neutral: 3 },
          weather: {
            ticker: "META",
            condition: "overcast",
            headline: "Bear overcast — risk cohort dominant",
            fragility: 0.41,
            fragility_label: "Fragile consensus",
            tally: { bullish: 2, bearish: 6, neutral: 3 },
            carried_by: [{ name: "Nassim Taleb", signal: "bearish", confidence: 84 }],
            top_disputes: [{ summary: "Ad cycle resilience vs regulatory tail risk" }],
            dominant_claim: "Regulatory tail underpriced",
            boss_action: "short",
            boss_confidence: 71,
            voice_count: 11,
          },
          disputes: [{ summary: "Ad cycle resilience vs regulatory tail risk" }],
          debateRounds: [],
        },
      ],
    },
  },
];
